// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proverbs/proverbs.proto

package proverbs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProverbsClient is the client API for Proverbs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProverbsClient interface {
	GetProverb(ctx context.Context, in *Timing, opts ...grpc.CallOption) (*Proverb, error)
}

type proverbsClient struct {
	cc grpc.ClientConnInterface
}

func NewProverbsClient(cc grpc.ClientConnInterface) ProverbsClient {
	return &proverbsClient{cc}
}

func (c *proverbsClient) GetProverb(ctx context.Context, in *Timing, opts ...grpc.CallOption) (*Proverb, error) {
	out := new(Proverb)
	err := c.cc.Invoke(ctx, "/proverbs.Proverbs/GetProverb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProverbsServer is the server API for Proverbs service.
// All implementations must embed UnimplementedProverbsServer
// for forward compatibility
type ProverbsServer interface {
	GetProverb(context.Context, *Timing) (*Proverb, error)
	mustEmbedUnimplementedProverbsServer()
}

// UnimplementedProverbsServer must be embedded to have forward compatible implementations.
type UnimplementedProverbsServer struct {
}

func (UnimplementedProverbsServer) GetProverb(context.Context, *Timing) (*Proverb, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProverb not implemented")
}
func (UnimplementedProverbsServer) mustEmbedUnimplementedProverbsServer() {}

// UnsafeProverbsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProverbsServer will
// result in compilation errors.
type UnsafeProverbsServer interface {
	mustEmbedUnimplementedProverbsServer()
}

func RegisterProverbsServer(s grpc.ServiceRegistrar, srv ProverbsServer) {
	s.RegisterService(&Proverbs_ServiceDesc, srv)
}

func _Proverbs_GetProverb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverbsServer).GetProverb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proverbs.Proverbs/GetProverb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverbsServer).GetProverb(ctx, req.(*Timing))
	}
	return interceptor(ctx, in, info, handler)
}

// Proverbs_ServiceDesc is the grpc.ServiceDesc for Proverbs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proverbs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proverbs.Proverbs",
	HandlerType: (*ProverbsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProverb",
			Handler:    _Proverbs_GetProverb_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proverbs/proverbs.proto",
}
